url: https://binaricorn.github.io
root: /

# Site settings
title: TRYTOBEGOOD
email: your-email@domain.com
description: "Designer, writer, tinkerer, current resident at DBRS Innovation Labs, and a DJ and talkshow host on bel-air radio with a MFA from Parsons Design and Technology."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/binaricorn
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty